### ISSUE TITLE
Get most recent scores in DM

### ISSUE THREAD

**Issue by jakerella** [jamesdabbs/marvin#6]
I would like to ask marvin for a summary of the most recent scores for a channel using a direct message. This would allow me to see at a glance how everyone is. While this does happen once the survey is complete... my channel rarely completes. Here is an example of the interaction I would like to see:

```
jordan: status #frontend_feb2017
marvin: here is the most recent status results for #frontend_feb2017...
  john: 3
  jill: 4
  james: (none)
  jane: 5
```

**Comment by rposborne** [comment]
@jakerella marvin is the individual sentient bot, this issue should be on https://github.com/jamesdabbs/lita-panic
